### ISSUE TITLE
Is your site SSG or SSR 

### ISSUE THREAD

**Issue by sarmadgardezi** [konstantinmuenster/konstantin.digital#6]
Secondly my quest is about SEO why your site dont build sitelinks on Google search can you work on it or explain ?

Is your website is SEO friendly compare to pages & blogs you post ?

**Comment by konstantinruge** [comment]
Hey @sarmadgardezi! 👋 The site uses React Server Components and is thus SSR. If you want to check out the SEO scores, you can inspect the deployed site with Google Lighthouse, for example. Please also note that this is my personal portfolio which I do not actively maintain for open-source users.

**Comment by sarmadgardezi** [comment]
sure as per checking perpose it have so many issues like image is attached below. Thats why i have asked.
![Uploading Screenshot 2023-11-20 at 1.45.51 PM.png…]()
